name: Bug and Error Report
description: Report a bug or error with the Find a Block plugin.
labels: ['bug']
body:
    - type: textarea
      attributes:
          label: Description
          description: Provide a more detailed explanation of what work needs to be done.
      validations:
          required: true

    - type: textarea
      attributes:
          label: Steps to recreate
          description: Please explain step-by-step how to reproduce this bug
      validations:
          required: true

    - type: textarea
      attributes:
          label: Screenshot or Recording
          description: Providing a screenshot or recording of the error is not required but can be helpful.
      validations:
          required: false

    - type: textarea
      attributes:
          label: Environment Details
          description: |
              Please provide information about your environment
          placeholder: |
              - What version of WordPress are you running?
              - What is your active theme?
              - Are you using a Mac or PC?
              - What browser and version are you using?
      validations:
          required: false

    - type: checkboxes
      attributes:
          label: Have you tested by deactivating all other active plugins?
          description: Confirm that you have tested with all other plugins deactivated to ensure there is no conflict.
          options:
              - label: 'Yes, I have deactivated all other plugins.'
                required: true

    - type: checkboxes
      attributes:
          label: Have you checked the existing issues to make sure this has not already been reported?
          description: Confirm that you have searched the existing issues.
          options:
              - label: 'Yes, I have checked the existing issues.'
                required: true
